services:
  mysql:
    image: "mysql:5.7"
    ports: # ポート3306を利用する
      - "3306:3306"
    volumes: # 永続化のため
      - mysql_data:/var/lib/mysql
    environment: # 環境変数を指定
      MYSQL_DATABASE: "***_web_development" # デフォルトdbを指定
      MYSQL_ROOT_PASSWORD: "***" # ユーザーrootならばこれでパスワードを指定する
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  rails: # 
    build: . 
    depends_on: # 上のmysqlの起動を待ってrailsを起動
      - mysql
    volumes:
      - .:/usr/src/app
      - vendor_bundle:/usr/src/app/vendor/bundle
    ports: # ポート3000を利用
      - "3000:3000"
    entrypoint: # 後述コマンド「docker-compose up」でコマンド「bin/rails s -b 0.0.0.0」が実行される
      - bin/rails
      - s
      - -b
      - 0.0.0.0